FROM ubuntu:latest
RUN apt-get -y update && apt-get -y install firefox && apt-get -y install vim-gtk3 && apt-get -y install verilator && apt-get -y install python3-pip 
WORKDIR /workspace
COPY . /workspace


